onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider PMU
add wave -noupdate /pmu_tb/pmu1/pmu0/data_i
add wave -noupdate /pmu_tb/pmu1/pmu0/en_i
add wave -noupdate /pmu_tb/pmu1/pmu0/rst_i
add wave -noupdate /pmu_tb/pmu1/pmu0/tck_i
add wave -noupdate /pmu_tb/pmu1/pmu0/checksum_en_i
add wave -noupdate /pmu_tb/pmu1/pmu0/progclk_o
add wave -noupdate /pmu_tb/pmu1/pmu0/flag_o_jtag
add wave -noupdate /pmu_tb/pmu1/pmu0/flag_o_fpga
add wave -noupdate /pmu_tb/pmu1/pmu0/data_o
add wave -noupdate /pmu_tb/pmu1/pmu0/data_ccff_i
add wave -noupdate /pmu_tb/pmu1/pmu0/data_ccff_o
add wave -noupdate /pmu_tb/pmu1/pmu0/state
add wave -noupdate /pmu_tb/pmu1/pmu0/next_state
add wave -noupdate /pmu_tb/pmu1/pmu0/header
add wave -noupdate /pmu_tb/pmu1/pmu0/counter0_o
add wave -noupdate /pmu_tb/pmu1/pmu0/counter1_o
add wave -noupdate /pmu_tb/pmu1/pmu0/counter0_en_r
add wave -noupdate /pmu_tb/pmu1/pmu0/counter1_en_r
add wave -noupdate /pmu_tb/pmu1/pmu0/counter0_en
add wave -noupdate /pmu_tb/pmu1/pmu0/counter1_en
add wave -noupdate /pmu_tb/pmu1/pmu0/capture
add wave -noupdate /pmu_tb/pmu1/pmu0/flag_o
add wave -noupdate /pmu_tb/pmu1/pmu0/ccff_en_r
add wave -noupdate /pmu_tb/pmu1/pmu0/capture_r
add wave -noupdate /pmu_tb/pmu1/pmu0/crc_en_r
add wave -noupdate /pmu_tb/pmu1/pmu0/crc_en
add wave -noupdate -divider CRC8
add wave -noupdate /pmu_tb/pmu1/pmu0/crc/clk_i
add wave -noupdate /pmu_tb/pmu1/pmu0/crc/en_i
add wave -noupdate /pmu_tb/pmu1/pmu0/crc/data_i
add wave -noupdate /pmu_tb/pmu1/pmu0/crc/capture_i
add wave -noupdate /pmu_tb/pmu1/pmu0/crc/flag_o
add wave -noupdate /pmu_tb/pmu1/pmu0/crc/data
add wave -noupdate /pmu_tb/pmu1/pmu0/crc/flag_o_r
add wave -noupdate -divider FPGA_Core
add wave -noupdate /pmu_tb/fpga_core/progclk
add wave -noupdate /pmu_tb/fpga_core/pReset
add wave -noupdate /pmu_tb/fpga_core/ccff_head
add wave -noupdate /pmu_tb/fpga_core/ccff_tail
add wave -noupdate /pmu_tb/fpga_core/data
add wave -noupdate -divider JTAG
add wave -noupdate /pmu_tb/pmu1/tap0/tms_i
add wave -noupdate /pmu_tb/pmu1/tap0/tck_i
add wave -noupdate /pmu_tb/pmu1/tap0/rst_ni
add wave -noupdate /pmu_tb/pmu1/tap0/td_i
add wave -noupdate /pmu_tb/pmu1/tap0/td_o
add wave -noupdate /pmu_tb/pmu1/tap0/shift_dr_o
add wave -noupdate /pmu_tb/pmu1/tap0/update_dr_o
add wave -noupdate /pmu_tb/pmu1/tap0/capture_dr_o
add wave -noupdate /pmu_tb/pmu1/tap0/memory_sel_o
add wave -noupdate /pmu_tb/pmu1/tap0/fifo_sel_o
add wave -noupdate /pmu_tb/pmu1/tap0/confreg_sel_o
add wave -noupdate /pmu_tb/pmu1/tap0/clk_byp_sel_o
add wave -noupdate /pmu_tb/pmu1/tap0/observ_sel_o
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_w_cs_sel_o
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_wo_cs_sel_o
add wave -noupdate /pmu_tb/pmu1/tap0/checksum_en
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_en
add wave -noupdate /pmu_tb/pmu1/tap0/scan_in_o
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_tdi_o
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_tck_o
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_rst_o
add wave -noupdate /pmu_tb/pmu1/tap0/memory_out_i
add wave -noupdate /pmu_tb/pmu1/tap0/fifo_out_i
add wave -noupdate /pmu_tb/pmu1/tap0/confreg_out_i
add wave -noupdate /pmu_tb/pmu1/tap0/clk_byp_out_i
add wave -noupdate /pmu_tb/pmu1/tap0/observ_out_i
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_tdo_i
add wave -noupdate /pmu_tb/pmu1/tap0/test_logic_reset
add wave -noupdate /pmu_tb/pmu1/tap0/run_test_idle
add wave -noupdate /pmu_tb/pmu1/tap0/sel_dr_scan
add wave -noupdate /pmu_tb/pmu1/tap0/capture_dr
add wave -noupdate /pmu_tb/pmu1/tap0/shift_dr
add wave -noupdate /pmu_tb/pmu1/tap0/exit1_dr
add wave -noupdate /pmu_tb/pmu1/tap0/pause_dr
add wave -noupdate /pmu_tb/pmu1/tap0/exit2_dr
add wave -noupdate /pmu_tb/pmu1/tap0/update_dr
add wave -noupdate /pmu_tb/pmu1/tap0/sel_ir_scan
add wave -noupdate /pmu_tb/pmu1/tap0/capture_ir
add wave -noupdate /pmu_tb/pmu1/tap0/shift_ir
add wave -noupdate /pmu_tb/pmu1/tap0/shift_ir_neg
add wave -noupdate /pmu_tb/pmu1/tap0/exit1_ir
add wave -noupdate /pmu_tb/pmu1/tap0/pause_ir
add wave -noupdate /pmu_tb/pmu1/tap0/exit2_ir
add wave -noupdate /pmu_tb/pmu1/tap0/update_ir
add wave -noupdate /pmu_tb/pmu1/tap0/idcode_sel
add wave -noupdate /pmu_tb/pmu1/tap0/memory_sel
add wave -noupdate /pmu_tb/pmu1/tap0/fifo_sel
add wave -noupdate /pmu_tb/pmu1/tap0/confreg_sel
add wave -noupdate /pmu_tb/pmu1/tap0/bypass_sel
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_w_cs_sel
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_wo_cs_sel
add wave -noupdate /pmu_tb/pmu1/tap0/clk_byp_sel
add wave -noupdate /pmu_tb/pmu1/tap0/observ_sel
add wave -noupdate /pmu_tb/pmu1/tap0/tdo_comb
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_tdi_o_reg
add wave -noupdate /pmu_tb/pmu1/tap0/tms_q1
add wave -noupdate /pmu_tb/pmu1/tap0/tms_q2
add wave -noupdate /pmu_tb/pmu1/tap0/tms_q3
add wave -noupdate /pmu_tb/pmu1/tap0/tms_q4
add wave -noupdate /pmu_tb/pmu1/tap0/tms_reset
add wave -noupdate /pmu_tb/pmu1/tap0/checksum_en_reg
add wave -noupdate /pmu_tb/pmu1/tap0/pmu_en_reg
add wave -noupdate /pmu_tb/pmu1/tap0/jtag_ir
add wave -noupdate /pmu_tb/pmu1/tap0/latched_jtag_ir
add wave -noupdate /pmu_tb/pmu1/tap0/latched_jtag_ir_neg
add wave -noupdate /pmu_tb/pmu1/tap0/instruction_tdo
add wave -noupdate /pmu_tb/pmu1/tap0/idcode_reg
add wave -noupdate /pmu_tb/pmu1/tap0/idcode_tdo
add wave -noupdate /pmu_tb/pmu1/tap0/bypassed_tdo
add wave -noupdate /pmu_tb/pmu1/tap0/bypass_reg
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {52780 ns} {53780 ns}
