#these will be done with default data types hex format from 0-16 with a Host PC to SC instruction

gen_mini:
	python3 bitstream_generator.py 128 "hex"
gen_small:
	python3 bitstream_generator.py 1024 "hex"
gen_medium:
	python3 bitstream_generator.py 262144 "hex"
gen_large:
	python3 bitstream_generator.py 524288 "hex"
gen_xlarge:
	python3 bitstream_generator.py 1048576 "hex"


