build:
	vlog -work work aes_128.v
	vlog -work work aes_128_tb.v
	vlog -work work aes_256.v
	vlog -work work aes_256_tb.v
	vlog -work work aes_round_128.v
	vlog -work work aes_round_256.v
	vlog -work work evolve_key.v
	vlog -work work evolve_key_256_tb.v
	vlog -work work mix_columns.v
	vlog -work work shift_rows.v
	vlog -work work sub_bytes.v
