# -*- Makefile -*-

WORK_LIB = pmu_lib
WORK_DIR = ${PROJECT_BUILD_DIR}/${WORK_LIB}

VERILOG_SOURCES += \
	config_chain.v \
	crc8.v \
	pmu.v \
	pmu_top.v \
	tap_top.v \

include ${PROJECT_CONFIG_DIR}/Makefile.def
