gen_tiny:
	python3 example_bitstream_script.py 128
gen_small:
	python3 example_bitstream_script.py 1024
gen_medium:
	python3 example_bitstream_script.py 524288
gen_large:
	python3 example_bitstream_script.py 1048576
